/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    brand?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StoreSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    lat: number | string;
                    lon: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/x-ndjson": components["schemas"]["PriceStreamEvent"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prices/store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    storeId: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PriceObservation"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prices/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    storeId: number | string;
                    product: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PriceObservation"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PriceObservation: {
            /**
             * Format: int64
             * @description The id of the store this price was observed at
             */
            storeId: number | string;
            /** @description The store brand */
            brand: string;
            /** @description The name of the store */
            storeName: null | string;
            /** @description The tracked product name */
            product: string;
            /**
             * Format: double
             * @description The observed price
             */
            price: number | string;
            /** @description The currency of the price */
            currency: string;
            /**
             * Format: date-time
             * @description When this price was observed
             */
            fetchedAt: string;
            /**
             * Format: date
             * @description If set, this price is not yet active - it becomes effective on this date (e.g. an upcoming sale). Null means the price reflects the store as currently observed.
             */
            effectiveFrom?: null | string;
            /** @description The page the price was fetched from, if known */
            sourceUrl?: null | string;
            /**
             * Format: date-time
             * @description When this price expires: the start of the day after it was fetched, in the store's local timezone. Prices are only valid on the day they were fetched. Null on raw history rows, where expiry carries no meaning.
             */
            validUntil?: null | string;
        };
        PriceStreamEvent: {
            /**
             * Format: int64
             * @description The id of the store this event reports on
             */
            storeId: number | string;
            /** @description Whether any price was found for this store - false if the store was checked but has no tracked prices */
            hasPrices: boolean;
            /** @description The prices observed for this store, empty when HasPrices is false */
            observations: components["schemas"]["PriceObservation"][];
        };
        StoreSummary: {
            /**
             * Format: int64
             * @description The id of the store, used as storeId in the /prices endpoints - same id as Services.POI's store id for this location
             */
            storeId: number | string;
            /** @description The store brand */
            brand: string;
            /** @description The name of the store */
            name: null | string;
            /**
             * Format: double
             * @description The latitude of the store, if known
             */
            latitude: null | number | string;
            /**
             * Format: double
             * @description The longitude of the store, if known
             */
            longitude: null | number | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
