// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Services.Prices.Database;

#nullable disable

namespace Services.Prices.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260826171407_AddPriceObservationEffectiveFrom")]
    partial class AddPriceObservationEffectiveFrom
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("MonberAPI.PoiData.Database.DbStore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpeningHours")
                        .HasColumnType("TEXT");

                    b.Property<string>("Shop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("stores", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Services.Prices.Database.DbPriceObservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StoreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StoreId", "Product", "FetchedAt");

                    b.ToTable("price_observations", (string)null);
                });

            modelBuilder.Entity("Services.Prices.Database.DbRefreshVersion", b =>
                {
                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastRefreshedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Brand");

                    b.ToTable("price_sync_versions", (string)null);
                });

            modelBuilder.Entity("Services.Prices.Database.DbStoreExternalId", b =>
                {
                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalStoreId")
                        .HasColumnType("TEXT");

                    b.Property<long>("StoreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Brand", "ExternalStoreId");

                    b.HasIndex("StoreId")
                        .IsUnique();

                    b.ToTable("store_external_ids", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
