services:
  monber-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:13.5"
    ports:
      - "18888"
    expose:
      - "18889"
      - "18890"
    networks:
      - "aspire"
    restart: "always"
  data-init:
    image: "busybox:latest"
    command:
      - "-c"
      - "chown 1000:1000 /data"
    entrypoint:
      - "sh"
    volumes:
      - type: "bind"
        target: "/data"
        source: "./data"
    networks:
      - "aspire"
  services-poi:
    image: "ghcr.io/c9glax/monber-services-poi:98e4e78daa3fd6048229d61155d367603158dd1b"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      ConnectionStrings__MonberDb: "Data Source=/data/monber.db"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://monber-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "services-poi"
    expose:
      - "8080"
    volumes:
      - type: "bind"
        target: "/data"
        source: "./data"
    depends_on:
      data-init:
        condition: "service_completed_successfully"
    user: "1000:1000"
    networks:
      - "aspire"
  flaresolverr:
    image: "ghcr.io/flaresolverr/flaresolverr:latest"
    expose:
      - "8191"
    networks:
      - "aspire"
  services-prices:
    image: "ghcr.io/c9glax/monber-services-prices:98e4e78daa3fd6048229d61155d367603158dd1b"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      FlareSolverr__Url: "http://flaresolverr:8191"
      ConnectionStrings__MonberDb: "Data Source=/data/monber.db"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://monber-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "services-prices"
    expose:
      - "8080"
    volumes:
      - type: "bind"
        target: "/data"
        source: "./data"
    depends_on:
      flaresolverr:
        condition: "service_started"
      services-poi:
        condition: "service_started"
      data-init:
        condition: "service_completed_successfully"
    user: "1000:1000"
    networks:
      - "aspire"
  frontend:
    image: "ghcr.io/c9glax/monber-frontend:98e4e78daa3fd6048229d61155d367603158dd1b"
    environment:
      NUXT_PUBLIC_MAP_TILER_KEY: "${MAPTILER_API_KEY}"
    expose:
      - "3000"
    networks:
      - "aspire"
  gateway:
    image: "ghcr.io/c9glax/monber-gateway:98e4e78daa3fd6048229d61155d367603158dd1b"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${GATEWAY_PORT}"
      SERVICES_POI_HTTP: "http://services-poi:8080"
      services__services-poi__http__0: "http://services-poi:8080"
      SERVICES_POI_HTTPS: "https://services-poi:8080"
      SERVICES_PRICES_HTTP: "http://services-prices:8080"
      services__services-prices__http__0: "http://services-prices:8080"
      SERVICES_PRICES_HTTPS: "https://services-prices:8080"
      FRONTEND_HTTP: "http://frontend:3000"
      services__frontend__http__0: "http://frontend:3000"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://monber-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "gateway"
    ports:
      - "${GATEWAY_PORT}"
    depends_on:
      services-poi:
        condition: "service_started"
      services-prices:
        condition: "service_started"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
